name: note自動投稿
on:
  schedule:
    - cron: '0 23,3,11 * * *'  # JST8/12/20時
  workflow_dispatch:
jobs:
  post:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: browser-actions/setup-playwright@v1
      with:
        playwright-version: '1.47.0'
    - env:
        NOTE_EMAIL: ${{ secrets.NOTE_EMAIL }}
        NOTE_PASSWORD: ${{ secrets.NOTE_PASSWORD }}
      run: npx playwright test post.spec.js --headed
